services:
  cmusic-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_URL=http://localhost:3000/api
    container_name: cmusic-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
